### ISSUE TITLE
Contributing to Open Source research 

### ISSUE THREAD

**Issue by nalasbali** [alexpetrov/Mentor-Bank#39]
Hi,

I am writing to invite you to participate in my PhD research which is about contributing to Open Source to modernize Computer Science education. The survey will take few minutes but will be of great value to my research as i need direct evidences from OS users like you, plz, to do my research. 

I hope you will be happy to participate by clicking on the related link to take the suitable survey & I appreciated your time so feel free to answer any number of questions (will be much help if you can answer all):
- Here you are the link to the mentor's survey: https://www.surveys.unsw.edu.au/f/161600/2b06/
- Here you are the link to the student's survey: https://www.surveys.unsw.edu.au/f/161584/5d1e/
- Here you are the link to the educator's survey: https://www.surveys.unsw.edu.au/f/161596/1191/
- Here you are the link to other experts & professionals from the OS industry:https://www.surveys.unsw.edu.au/f/161607/11a8/

"Please support my PhD research by circulating this invitation and mention it to your friends to reach educators, students, mentors & other experts & professional interested in the OS field"

[Participant Implied Consent Statement.pdf](https://github.com/alexpetrov/Mentor-Bank/files/107730/Participant.Implied.Consent.Statement.pdf)

Many thanks in advance,,
Nada Alasbali
PhD of Computer Science & Engineering
University of New South Wales, Australia

**Comment by alexpetrov** [comment]
Hello, Nada!

Thank you for consideration. I was a bit surprised :)
Unfortunately I don't meet the requirements for your research.
I used to be an formal educator and my students didn't contribute to any serious open source projects.
This project "Mentor-Bank" is absolutely synthetic and trivial meant to be used as an exercise in Java/Spring programming, TDD and using Git and GitHub.

Sorry, that I can't help you.

Wish you great success with your research! I believe in Open Source and FSF!
